# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75a8e71f8f5feae5924a646499ec8d970351ed9a197351a25f2b1e9967b8ab9c4a1c8e362db22c81871a34229d6478b1b0e4ea6b415ca1314555623b6d27cc4d

test:
  secret_key_base: abd36bec4b64840f295f90a2f623c177c7e9c7c3ec1db2d802daf383cc87069f7c238a7c3293fa02d2e789a513d21298b27c65e9a421b0ca3a40f39da09969ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
